version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - my-network
  message-broker:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672" # Management Plugin
    networks:
      - my-network

networks:
  my-network:
    driver: bridge